### ISSUE TITLE
Better styling of the github pages

### ISSUE THREAD

**Issue by vidstige** [vidstige/pascaljs#26]
The github pages over at https://vidstige.github.io/pascaljs/ looks a bit... quickly done. Which is true! I like the dark theme of the code editor, but the rest of the page this not follow along. If you don't like the code editor theme, [it can be changed](https://github.com/vidstige/pascaljs/blob/master/docs/index.html#L30), and there are plenty of [others](https://github.com/ajaxorg/ace/tree/master/lib/ace/theme) to choose from.

Anyway, it would be good if the rest of the page was in line with the code editor when it comes to font color, font size, background color. If somebody could fix one of these things, it would be warmly welcome.

Thanks in advance.

**Comment by keepitrio** [comment]
Hey, I can take this! :) I've contributed once but it was alphabetizing a Gemfile, just to get my fingers wet.

**Comment by keepitrio** [comment]
[Pull request](https://github.com/vidstige/pascaljs/pull/28) created. 

Let me know what you think!
